version: '3'

services:
###> doctrine/doctrine-bundle ###
  app:
    image: ss/php:8-symfony
    depends_on:
      - database
    volumes:
      - .:/src

  nginx:
    image: ss/nginx:8-symfony
    depends_on:
      - app
    volumes:
      - .:/src
    ports:
      - "8000:80"

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-multimedia}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Zambou}
      POSTGRES_USER: ${POSTGRES_USER:-MEZATIO}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data: {}
###< doctrine/doctrine-bundle ###
